name: Build

on:
  workflow_dispatch:
  push:
    branches: 
    - limine
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup
        shell: bash
        run: echo hi
        
